version: '3.9'
services:
  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      # shared env file with strapi application
        - ./apps/backend/.env
    volumes:
      - ./db-data/:/var/lib/postgresql/data
    restart: unless-stopped

  frontend:
    container_name: frontend
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    networks:
      - turbo-network

networks:
  turbo-network:
    driver: bridge