version: '3.9'
services:
  frontend:
    container_name: frontend
    build:
      context: ./apps/front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/front:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    networks:
      - turbo-network

  backend:
    container_name: backend
    build:
      context: ./apps/back
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=development
      - DATABASE_CLIENT=sqlite
      - DATABASE_FILENAME=.tmp/data.db
    volumes:
      - ./apps/back:/app
      - /app/node_modules
      - /app/.tmp
    restart: unless-stopped
    networks:
      - turbo-network

networks:
  turbo-network:
    driver: bridge
