import RootLayoutClient from "@/components/layout/RootLayoutClient";
import { LocaleProvider } from "@/contexts/LocaleContext";
import { getAvailableLocales, getGlobalSettings } from "@/data/loaders";
import type { Metadata } from "next";
import { Baloo_2 } from "next/font/google";
import "./globals.css";

const baloo2 = Baloo_2({
  variable: "--font-baloo",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Just'In Com",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Get data for all available locales
  const availableLocales = await getAvailableLocales();
  const localeCodes = availableLocales.map((locale: { code: string }) => locale.code);

  // Fetch global settings for each locale
  const globalSettingsByLocale = await Promise.all(
    localeCodes.map(async (locale: string) => {
      const settings = await getGlobalSettings(locale);
      return { locale, settings };
    })
  );

  // Get the initial locale from the first available locale
  const initialLocale = localeCodes[0];

  return (
    <LocaleProvider initialLocale={initialLocale}>
      <RootLayoutClient
        globalSettingsByLocale={globalSettingsByLocale}
        availableLocales={localeCodes}
        fontClassName={baloo2.variable}
      >
        {children}
      </RootLayoutClient>
    </LocaleProvider>
  );
}
